### ISSUE TITLE
Hosting docs online

### ISSUE THREAD

**Issue by vigji** [3d-pli/fastpli#4]
It would be highly recommended if the full documentation of the package is hosted somewhere, on GitHub Pages or ReadTheDocs, instead of having this to be run on the user's side and stored locally (in this case, the `sphinx-rtd-theme` and the `sphinx-autodoc-typehints` deps are missing)

**Comment by vigji** [comment]
Also, once fixed the dependency issue the docs index.html file is an empty page

**Comment by fmatuschke** [comment]
This is a very good recommendation. I added an automatic process to publish the module documentation to a GitHub Page <https://3d-pli.github.io/fastpli/> at every release step.

As you probably can see, the module documentation is currently not finished. I am working on adding doc strings to all methods and adding additional information to the page. I am also thinking about merging the Wiki to the GitHub Page so that everything is combined. If I find a fast and nice looking solution for this I will integrate it.

I will update everything with a new version of the wiki that also takes #5 and #6 into account.

**Comment by fmatuschke** [comment]
The publishing process of the API documentation seems to work fine. I can of course be further improved. At this point I think however I can close this issue. Thanks again for the suggestion.
